from __future__ import annotations

MENU_LIVE_STATUS = "Live"

(
    API_ID_STATE,
    API_HASH_STATE,
    REPORT_SESSIONS,
    TARGET_KIND,
    REPORT_URLS,
    REPORT_REASON_TYPE,
    REPORT_MESSAGE,
    REPORT_COUNT,
    SESSION_MODE,
) = range(9)
ADD_SESSIONS = 10
PRIVATE_INVITE = 11
PRIVATE_MESSAGE = 12
PUBLIC_MESSAGE = 13
STORY_URL = 14

DEFAULT_REPORTS = 5000
MIN_REPORTS = 500
MAX_REPORTS = 7000
MIN_SESSIONS = 1
MAX_SESSIONS = 500

REASON_LABELS = {
    0: "Spam",
    1: "Violence",
    2: "Pornography",
    3: "Child abuse",
    4: "Copyright",
    5: "Other",
    6: "Illegal content",
}

__all__ = [
    "MENU_LIVE_STATUS",
    "API_ID_STATE",
    "API_HASH_STATE",
    "REPORT_SESSIONS",
    "TARGET_KIND",
    "REPORT_URLS",
    "REPORT_REASON_TYPE",
    "REPORT_MESSAGE",
    "REPORT_COUNT",
    "SESSION_MODE",
    "ADD_SESSIONS",
    "PRIVATE_INVITE",
    "PRIVATE_MESSAGE",
    "PUBLIC_MESSAGE",
    "STORY_URL",
    "DEFAULT_REPORTS",
    "MIN_REPORTS",
    "MAX_REPORTS",
    "MIN_SESSIONS",
    "MAX_SESSIONS",
    "REASON_LABELS",
]
